### ISSUE TITLE
Flock <-> CardDAV/CalDAV bridge (for Desktop clients)

### ISSUE THREAD

**Issue by Natanji** [WhisperSystems/Flock#16]
I think Flock is nice and all, but for my particular use case it's rather useless because I need to sync my Calendars with the desktop (Windows and Linux, in my case) and apps that are supported there (e.g. Thunderbird with Lightning).

I think changing lots of Desktop clients and creating plugins for them might be way too much work. Therefore I propose that a bridging app should be written. It could simply be a local CardDAV/CalDAV server that is only available locally (and with user/password additionally to protect data from other accounts on the same machine). The local storage could then be synced with Flock.

**Comment by patcon** [comment]
Somehow some convo on the encryption proxy started happening in another issue (https://github.com/WhisperSystems/Flock/issues/42#issuecomment-67567081), but perhaps we could move it back here?

**Comment by patcon** [comment]
Ref: https://github.com/rhodey/flock-desktop
