### ISSUE TITLE
Disconnecting Flock account requires factory reset

### ISSUE THREAD

**Issue by patcon** [WhisperSystems/Flock#81]
During testing, found that Flock accounts can't easily be removed without wiping the whole device. This is an edge case, but seems rather drastic, especially if someone wants to move from OWS hosted to self-hosted.

Here's how I tried to remove it:

    Settings > Accounts > Flock > [ACCOUNT NAME] > More >  Remove account [confirm]

This was the dialog that popped up, and I could only hit "OK":

> This account is required by some apps. You can only remove it by resetting the tablet to factory defaults (which deletes all your personal data) in Settings > Backup & reset.

Clearing all data from Flock app did not resolve the issue. Also, fwiw I'd destroyed the sync server at this point, so there was a pending sync error before attempting to disconnect.

Uninstalling the Flock app might work, but I can't do that right now as I'm testing other things and cant' easily reinstall via adb atm. If uninstall solves it, then clarifying that might be helpful.

**Comment by rhodey** [comment]
no way to hijack the "remove account" button :[
