### ISSUE TITLE
Days Remaining on Subscription seems inccorrect

### ISSUE THREAD

**Issue by zmanian** [WhisperSystems/Flock#86]
I subscribed via the Stripe interface a while ago.

Interface says 8879 days remaining in subscription which seems wrong probably. 

![screenshot_2015-01-27-10-14-43](https://cloud.githubusercontent.com/assets/93434/5924105/a0a46304-a60d-11e4-8735-86949be13542.png)

**Comment by rhodey** [comment]
there have been a handful of people that have been especially helpful with debugging Flock issues related to the dreaded protocol migration of 2014. many of these people got lots of free credit on their account or some other form of gratitude, you were one of them :)
