### ISSUE TITLE
some contacts fail to import due to size of pictures

### ISSUE THREAD

**Issue by rhodey** [WhisperSystems/Flock#88]
import of select contacts fails in certain edge cases where the amount of data processed in a ContentProvider batch operation exceeds 1MB. so far this bug has only been spotted on Lolipop devices.

**Comment by nysatrok** [comment]
Could this bug be related to #83?

**Comment by rhodey** [comment]
@nysatrok it is possible, let me know if the new version helps! resolved by bbff2a5a344f8b828ea8cf65bf86bec94b52d833

**Comment by nysatrok** [comment]
@rhodey Sadly, the issue #83 still occurs.
